spin_manifest_version = 2

[application]
name = "glinder"
version = "0.1.0"
authors = ["Daniel Kuschel <danielkaes@duck.com>"]
description = "A dating app for lonely gloves."

[variables]
username = { required = true }
password = { required = true }

[[trigger.http]]
route = "/api/..."
component = "image-upload"

[[trigger.http]]
route = "/upload.html"
component = "image-upload"

[[trigger.http]]
route = "/admin.html"
component = "image-upload"

[[trigger.http]]
route = "/edit.html"
component = "image-upload"

[component.image-upload]
source = "target/wasm32-wasip1/release/image_upload.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]
[component.image-upload.variables]
username = "{{ username }}"
password = "{{ password }}"
[component.image-upload.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "glinder"

[component.glinder]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "www", destination = "/" }]
